### ISSUE TITLE
Question: Is this 'run' line supposed to start Meteor app?

### ISSUE THREAD

**Issue by yzalvov** [tozd/docker-meteor#10]
@mitar please clarify, is this `docker run` line supposed to start a Meteor app?
https://github.com/tozd/docker-meteor/blob/0243be1bc523d514a105cc38e2c8cfac4a5980aa/run.sh#L51
Or do I need to use `node bundle/main.js` myself?
I'm asking because in my case I have to run the command to have the app running. 

As a side note, I can see some "meteor activity" lines in MongoDB log file and a couple of meteor relevant processes before running `node bundle/main.js`:
```console
ps -ax
  PID TTY      STAT   TIME COMMAND
    1 ?        Ss     0:01 runsvdir -P /etc/service log: e/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/operations/mongo_client_ops.js:240:5)     at process.nextTic
    8 ?        Ss     0:00 runsv meteor
    9 ?        S      0:00 svlogd -tt /var/log/meteor
```

Many thanks for considering my question.

**Comment by mitar** [comment]
> Or do I need to use node bundle/main.js myself?

No. Meteor app starts automatically through [this service](https://github.com/tozd/docker-meteor/blob/master/etc/service/meteor/run). But you should make sure you have changed Docker image entrypoint.

From what you provided it looks like the service has started, but had some issues. You should look into `/var/log/meteor` for more information why it does not run for you, this is where things get logged.
