### ISSUE TITLE
Option for specific meteor version

### ISSUE THREAD

**Issue by thoaif** [tozd/docker-meteor#17]
Is it possible to have an environment variable for specifying the version of Meteor to download. Currently, the image always download the latest version. 

Changing the current meteor install command to:

`curl https://install.meteor.com/?release=$METEOR_VERSION`

would do the trick. By default, `METEOR_VERSION` could be set to "latest", which also works.

I have been using a meteor app that I first deployed on meteor 1.6.0. During an update, the latest meteor version was downloaded causing the build to fail.

**Comment by mitar** [comment]
Hm, the latest meteor version should still download an older Meteor version to build the app? At least it worked in the past for me like that. Maybe they changed with latest version something.

I think this is reasonable, feel free to make a PR.

**Comment by thoaif** [comment]
In that case, there maybe a deeper issue in the script that is creating a conflict between npm/node versions. I will keep looking into this.

In the meantime, I have created PR #18 for including the meteor version as a build arg.

**Comment by mitar** [comment]
Done in #18.
