### ISSUE TITLE
Meteor 1.5 EISDIR: illegal operation on directory

### ISSUE THREAD

**Issue by QHose** [tozd/docker-meteor#3]
![image](https://user-images.githubusercontent.com/12411165/27767688-80120526-5eff-11e7-91b2-722df0fe546e.png)

I tested with this [repo](https://github.com/QHose/QRSMeteor)

**Comment by mitar** [comment]
Who is calling this `sudo chown -Rh ...` command? Where is this coming from? What does it have with this image?

**Comment by mitar** [comment]
So when does this happen?

Can you make me a branch or something of the repo, with clear instructions how to reproduce this?

**Comment by QHose** [comment]
Hi,

The solution is to

`I got it working by manually removing all directories and links where the name started with "dev_bundle" inside the "/.meteor/local" directory.
`
So maybe good to add this in the dockerfile



The information transmitted is intended only for the person or entity to which it is addressed and may contain confidential and/or privileged material. Any review, retransmission, dissemination or other use of, or taking of any action in reliance upon, this information by persons or entities other than the intended recipient is prohibited. If you received this in error, please contact the sender and delete the material from any computer.

**Comment by mitar** [comment]
`.meteor/local` inside your local repo?

I think you should add `.meteor/local` to `.dockerignore` in your local repo. I think this might be an issue?

I would propose you use Docker Hub to build images, then you do not have to worry about your local repository being dirties by local development files. Which it seems to me happens here.

**Comment by mitar** [comment]
See new README on how to use `.dockerignore`.

**Comment by mitar** [comment]
Please check if the new Dockerfile fixes your problem.

**Comment by QHose** [comment]
Thanks will do!

Verstuurd vanaf mijn iPhone

Op 7 jul. 2017 om 21:04 heeft Mitar <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


See new README on how to use .dockerignore.

**Comment by QHose** [comment]
Ah Thats a cool Solution! You are right...

Verstuurd vanaf mijn iPhone

Op 6 jul. 2017 om 13:55 heeft Mitar <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


.meteor/local inside your local repo?

I think you should add .meteor/local to .dockerignore in your local repo. I think this might be an issue?

I would propose you use Docker Hub to build images, then you do not have to worry about your local repository being dirties by local development files. Which it seems to me happens here.
