### ISSUE TITLE
Trying to run on Kubernetes - meteor app does not seem to have started

### ISSUE THREAD

**Issue by adamgins** [tozd/docker-meteor#6]
Hi,  thanks for the package... 

when I run on a local docker images, all seems to work OK
When I try and run on Kubernetes it does not seems to start the app - or perhaps I cannot see the logs???

Any ideas please?

I noticed https://github.com/kubernetes/kubernetes/blob/master/examples/meteor/dockerbase/Dockerfile
has this coe to kick off running the app

`ENTRYPOINT MONGO_URL=mongodb://$MONGO_SERVICE_HOST:$MONGO_SERVICE_PORT /usr/local/bin/node main.js`

I was not 100% sure where this happened in this Docker base image?

I guess there's a related side question... anything special to get the logs showing up on Kubernetes?

**Comment by mitar** [comment]
This image can definitely run on Kubernetes. :-)

Meteor is run by rinit, not through the entrypoint.

You can set `LOG_TO_STDOUT` ENV variable to something and it will output logs to stdout. Otherwise they are stored in `/var/log/meteor`. You can mount a volume to `/var/log/meteor` to store logs outside of the container.

**Comment by adamgins** [comment]
@mitar cool thanks for the quick reply. Turned logging on and I can see I have issue with my settings... is there a easy way to pass a settings.json file ?

when I was running Docker locally I was doing...

```
export METEOR_SETTINGS=""$(cat ./settings.json)
docker run --rm \
-e METEOR_SETTINGS="$METEOR_SETTINGS" \
```

which worked well.

**Comment by mitar** [comment]
Yes, you can put settings into an environment variable even with Kubernetes. Is that a problem?

**Comment by adamgins** [comment]
I must be stuffing it up somehow 

I tried passing it in the yaml file as      #   cpu: 100m
          env:
            - name: LOG_TO_STDOUT
              value: "1"
            - name: METEOR_SETTINGS
              value: '{	"AWS": { .... ending with '

But still seems to be messed up.. is there an example somewhere of passing a complex METEOR_SETTINGS/settings.json pls or is there some way to reference the file as I do in the `.sh` file (as above)?

**Comment by mitar** [comment]
I am glad it works. One other thing I think you can do in YAML is also:

```yaml
env:
  - name: METEOR_SETTINGS
     value: |
       {raw JSON}
```

**Comment by adamgins** [comment]
ok, cool... yep not a YAML guru about a longshot. 

I am actually gettinga 503/Bad Gateway nginX issue now... any ideas on that, pls? 
I can see my app has started... just no traffic getting to it. 
So probably some kubernetes config issue
Also what do I need for sticky sessions etc?

**Comment by mitar** [comment]
Sorry, I do not have time at the moment to debug this for you.
