### ISSUE TITLE
Env vars from mounted run.config don't work

### ISSUE THREAD

**Issue by yzalvov** [tozd/docker-meteor#9]
Hi Mitar
Thanks for the Docker image set (Meteor, MongoDB, Nginx). I managed to run Mongo successfully, but Meteor is a problem. I built the image. Then start it with the same `run.config` as MongoDB image, it eats up like 30% of my host CPU and nothing. I may be far from having enough experience with Docker to debug things out, but I can't even get any logging info from my Meteor container. `${DATA_ROOT}/${NAME}/meteor/log` is empty and I can't get anything to stdout. Please help.

**Comment by yzalvov** [comment]
To run I use `run.sh` based on your `run.sh` with the following line:
```posh
docker run --detach=true --restart=always --name mymeteor --network mynet --volume "${CONFIG}:/etc/service/meteor/run.config" --volume "${METEOR_LOG}:/var/log/meteor" mymeteor-image
```
Then I managed to get in: 
```console
$ docker exec -it mymeteor bash
```
Then I can see my `run.config` inside: 
```console
root@31c2d1abb050:/# cat etc/service/meteor/run.config 

MONGODB_ADMIN_PWD='testPass18'
MONGODB_CREATE_PWD='testPass18'
MONGODB_OPLOGGER_PWD='testPass18'

export ROOT_URL="http://localhost:3000"
export MONGO_URL="mongodb://meteor:${MONGODB_CREATE_PWD}@mongodb/meteor"
export MONGO_OPLOG_URL="mongodb://oplogger:${MONGODB_OPLOGGER_PWD}@mongodb/local?authSource=admin"
```
But env vars are not as expected:
```console
root@31c2d1abb050:/# printenv
MAIL_URL=smtp://user:password@mailhost:port/
HOSTNAME=31c2d1abb050
TERM=xterm
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
METEOR_SETTINGS={}
PWD=/
MONGO_URL=mongodb://mongodb/meteor
ROOT_URL=http://example.com
SHLVL=1
HOME=/
DEBIAN_FRONTEND=noninteractive
LOG_TO_STDOUT=0
PORT=3000
MONGO_OPLOG_URL=mongodb://mongodb/local
_=/usr/bin/printenv
```
Please advise what did I miss?

**Comment by yzalvov** [comment]
I finally managed to run the container successfully but only feeding all the env vars to `docker run` command in `run.sh` mentioned above. Passing the env vars inside the container through the mounted `run.config`, as [README.md](https://github.com/tozd/docker-meteor/blob/master/README.md) suggests, didn't work for me. 

To be more clear I updated the issue title.

**Comment by diavrank** [comment]
For me, neither doesn't work. I have to enter into the container to set the env variables, but neither works.

I execute the `node main.js` command and it launches this error:

```
MongoNetworkError: failed to connect to server [mongodb:27017] on first connect [MongoNetworkError: getaddrinfo ENOTFOUND mongodb mongodb:27017]
    at Pool.<anonymous> (/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/topologies/server.js:564:11)
    at emitOne (events.js:116:13)
    at Pool.emit (events.js:211:7)
    at Connection.<anonymous> (/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:317:12)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at Connection.emit (events.js:214:7)
    at Socket.<anonymous> (/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/connection.js:246:50)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickDomainCallback (internal/process/next_tick.js:219:9)
```

**Comment by mitar** [comment]
@diavrank I think in your case you have to make sure your container can connect to MongoDB first. First debug why this seems to be a problem in your case. Only after you can yourself make the connection from Meteor container to MongoDB container, only then you might have luck getting Meteor to connect as well.

> But env vars are not as expected:

Yes, those are set only for Meteor service. [See here](https://github.com/tozd/docker-meteor/blob/master/etc/service/meteor/run#L12).
